version: '3.8'

services:
  app:
    container_name: "app"
    hostname: "app"
    env_file:
      - .env
    build:
      context: ./src
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./src:/code
    working_dir: /code
    command: ash -c "python app.py"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - redis
      - postgres
  
  postgres:
      image: postgres:14-alpine
      container_name: postgres
      restart: always
      env_file:
        - .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports: 
        - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
      volumes:
        - ./db/postgres-data:/var/lib/postgresql

  redis:
    container_name: "redis"
    hostname: "redis"
    image: redis:alpine
    command: /bin/ash -c "redis-server --requirepass ${REDIS_PASSWORD}"
    env_file:
      - .env
    restart: always
    ports:
      - ${REDIS_EXTERNAL_PORT}
    volumes:
      - ./db/redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G