version: '3.8'

services:
  redis-dev:
    container_name: "redis-db-dev"
    hostname: "redis-db-dev"
    image: redis:alpine
    command: /bin/ash -c "redis-server --requirepass ${REDIS_PASSWORD}"
    env_file:
      - .env
    restart: always
    ports:
      - 6379:6379  # "6379:6379"  #redis-server
    expose:
      - 6379 # 6379
    volumes:
      - ./db/redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G