version: '3.8'

services:
  app:
    container_name: "app"
    hostname: "app"
    env_file:
      - .env
    build:
      context: ./src
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./src:/code
    working_dir: /code
    command: ash -c "python app.py"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - redis

  redis:
    container_name: "redis"
    hostname: "redis"
    image: redis:alpine
    command: /bin/ash -c "redis-server --requirepass ${REDIS_PASSWORD}"
    env_file:
      - .env
    restart: always
    ports:
      - 6379:6379  # "6379:6379"  #redis-server
    expose:
      - 6379 # 6379
    volumes:
      - ./db/redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G